---
title: "Statistics on the Rennes website"
author: "Camille, Constance, Henri et Frédéric - Lannion"
date: "14 septembre 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!-- getting datas -->
```{r, include=FALSE}
  data = read.csv("https://raw.githubusercontent.com/camilleguerry/stat-sur-le-site-de-Rennes/master/statistiques-de-frequentation-du-site-rennes-metropole-en-acces-libre.csv",sep=";")
  names(data) = c("Date","NumberOfVisitors","NumberOfPageViews")
```
##Number of page views
```{r dataViewedPage}
library(ggplot2)
ggplot(data = data, aes(x=Date, y=NumberOfPageViews)) + geom_point() + ylab("Number of page views") + ggtitle("Number of page views (by user) in functions of the date")
```

##Number of visitors
```{r dataVisitors}
library(ggplot2)
ggplot(data = data, aes(x=Date, y=NumberOfVisitors)) + geom_point() + ylab("Number of visitor") + ggtitle("Number of visitor in functions of the date")
```

##Mean of page viewed per visitors
```{r dataMeanPageVisitors}
library(ggplot2)
ggplot(data = data, aes(x=Date, y=NumberOfPageViews/NumberOfVisitors)) + geom_point() + ylab("Number of page views per visitors") + ggtitle("Number of page views per visitor in functions of the date")
```
```{r}
library(stringr)
dates2017 = data[str_detect(data$Date,"2017"),]
tmp=dates2017 %>% group_by(str_sub(dates2017$Date, 6, 7)) 
tmp
names(tmp) = c("Date","Utilisateurs","PagesVues", "Month")
tab = aggregate(tmp$Utilisateurs, by=list(Month=tmp$Month), FUN=sum)
tab
barplot(tab$x, main="Title",xlab="MONTH", ylab="Number of users",names.arg = c("Jan","Fe","Mar","Ap","M","J","J","A","S"))

```

